### ISSUE TITLE
RFE:  A few items which would be nice to have

### ISSUE THREAD

**Issue by thefunkygibbon** [htmltiger/config-editor#1]
Hi, great great addition to HA.  I've been thinking that a way of editing the yaml within the browser was an essential missing part of HA since i started using it.   I don't have to use code-server anymore! 

1)   Option to add shortcut button to the left hand list of sections (ie somewhere in between Overview, Energy, Map etc (prob more at the bottom though) It must be possible to do given that I've just installed a different component via HACS called dwaines dashboard and it has added an item in that list.   It would be a bit easier than using a card to do the editing

2)  Option to auto open a specific file

3)  Option to chose from other commonly editable file formats, such as .js or .css

**Comment by tamimology** [comment]
For the first one. I have solved it by having a new lovelace dashboard and have the card in that as a single entity. It works as a charm on mobile
![Screenshot_20211230-094004_Home Assistant](https://user-images.githubusercontent.com/90429593/147708590-169057df-c717-4bbf-b312-da779b0f8f21.png)
![Screenshot_20211230-093932_Home Assistant](https://user-images.githubusercontent.com/90429593/147708593-ff80e9fb-6cc8-45ed-8f4f-d408dd7d1510.png)
![Screenshot_20211230-093951_Home Assistant](https://user-images.githubusercontent.com/90429593/147708599-48c12030-bd6a-43cd-8131-261ce041f51e.png)

**Comment by thefunkygibbon** [comment]
Nice. Thanks. Is that last picture implying that it auto opens the config file for you too?

**Comment by tamimology** [comment]
No it does not open automatically. I opened it for illustration purposes only to show you how ot looks on mobile using my suggestion above

**Comment by thefunkygibbon** [comment]
Ah ok. Thanks then for that, I wasn't sure how these dashboard things work as it asks for a URL but doesn't accept normal URLs so it's always left me confused.  I will look into doing what you suggested later today

**Comment by htmltiger** [comment]
added auto load and other file types support
