### ISSUE TITLE
Not loaded in Lovelace 

### ISSUE THREAD

**Issue by FpazHn** [htmltiger/config-editor#10]
I get the following message when going into hacs related to config-editor.

"You have 1 Lovelace elements that are not loaded properly in Lovelace."

The rest of the editor works perfectly.

Thanks in advance for your help

**Comment by htmltiger** [comment]
How did you install it? 

I dont see that message, may be you have some issues with hacs.
uninstall the addon and delete folder /www/community/config-editor-card if its still in there and then reinstall.

[try workarounds](https://www.reddit.com/r/homeassistant/comments/tk6dk1/hacs_and_mushroom_and_why_am_i_having_trouble/)

**Comment by mikecar66** [comment]
I donor know if I had the exact same issue. I had today also the similar message. Installation in docker on my Qnap NAS . I downloaded the config editor card again and got a message I need to add resources manually (see the pictures). After adding the resource manually the card loaded and worked !

**Comment by mikecar66** [comment]
![77ADEE63-1BDC-45CA-97E6-8B1BC67EC458](https://user-images.githubusercontent.com/126167242/231556384-b4e86f09-46a6-4df4-b61a-79fbafc0306e.png)
![B65BA3AC-F7D0-4EB3-B15A-D4D25EF139D7](https://user-images.githubusercontent.com/126167242/231556393-e3831469-899c-4b54-8f63-235a05252adb.png)

**Comment by htmltiger** [comment]
good to know it worked
