### ISSUE TITLE
config_editor.version does not have a unique ID

### ISSUE THREAD

**Issue by Sanbecr** [htmltiger/config-editor#14]
The Config Editor Version entity (config_editor.version) does not have a unique ID, which means it is not possible to edit, e.g. to hide it from the dashboard.
When trying to edit it Home Assistant reports:
> This entity ('config_editor.version') does not have a unique ID, therefore its settings cannot be managed from the UI. See the 
> [documentation](https://www.home-assistant.io/faq/unique_id) for more detail.

![SCR-20240308-tul](https://github.com/htmltiger/config-editor/assets/115875468/a01a709a-0e8e-4dfe-83df-96737d32d08e)

**Comment by htmltiger** [comment]
There is nothing in there to manage settings, it is just a version tag which frontend (config-editor-card) looks if you have installed the correct "config-editor" or need upgrade.
any settings will need to be done in [frontend](https://github.com/htmltiger/config-editor-card?tab=readme-ov-file#advanced-config)

**Comment by egormanga** [comment]
I suggest reopening this, as there's still no way of hiding that `version` sensor from the Lovelace auto-generated dashboard. It should have the `diagnostic` entity category set.
