### ISSUE TITLE
Some Enhancements

### ISSUE THREAD

**Issue by tamimology** [htmltiger/config-editor#2]
I was thinking if the custome component would have the 3 options below

1- Sort the yaml files in alphabetical order as it would be easier to find the file needed

2- create a new yaml file and start editing it

3-(could be difficult) to have a save option fixed on top even when scrolling the yaml file instead of going all the way up to save

Other than that I find it complete for now. Keep it up mate

**Comment by htmltiger** [comment]
1. Added in 1.3
2. New files can be created, just type some text and hit save, leave blank in dropdown menu

**Comment by tamimology** [comment]
Awesome. Keep it up. 

Thanks mate.
