### ISSUE TITLE
Not showing files after 3 subfolders

### ISSUE THREAD

**Issue by GRiDlockUK** [htmltiger/config-editor#5]
pi@Pi4:~/docker/home-assistant/dwains-dashboard $ tree
.
├── addons
│   ├── house_information
│   │   └── statistics.yaml    <--- does not show in get files
└── configs
    ├── cameras.yaml
    ├── global.yaml
    ├── house_information.yaml
    ├── icons.yaml
    ├── more_page.yaml
    ├── persons.yaml
    └── rooms.yaml

**Comment by htmltiger** [comment]
It is limited, change the following file from 2 to 5 and it should work.

https://github.com/htmltiger/config-editor/blob/1a37682e32294b5f776d82ff98c2ea708e9c3c49/custom_components/config_editor/__init__.py#L52
